# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=244, null=True, unique=True, verbose_name='论文标题')),
                ('cit_num', models.IntegerField(default=0, verbose_name='引用数量')),
                ('description', models.TextField(null=True, verbose_name='标签简述')),
                ('creator', models.TextField(null=True, verbose_name='作者')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('url', models.TextField(null=True, verbose_name='链接de')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, unique=True, verbose_name='作者名')),
                ('description', models.TextField(null=True, verbose_name='作者简述')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('url', models.TextField(null=True, verbose_name='链接a')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=244, null=True, unique=True, verbose_name='论文标题')),
                ('cit_num', models.IntegerField(default=0, verbose_name='引用数量')),
                ('description', models.TextField(null=True, verbose_name='标签简述')),
                ('creator', models.TextField(null=True, verbose_name='作者')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('url', models.TextField(null=True, verbose_name='链接de')),
                ('authors', models.ManyToManyField(to='api.Author', verbose_name='作者')),
                ('cit_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Paper')),
            ],
        ),
        migrations.AddField(
            model_name='aa',
            name='authors',
            field=models.ManyToManyField(to='api.Author', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='aa',
            name='cit_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Aa'),
        ),
    ]
