# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aa',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='aa',
            name='cit_paper',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=244, null=True, unique=True, verbose_name='作者名'),
        ),
        migrations.DeleteModel(
            name='Aa',
        ),
    ]
